# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"

# 3つの環境で共通して参照する設定を定義
default: &default
  adapter: mysql2
  # DB接続時に使用する文字コード
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  host: <%= ENV['MYSQL_HOST'] || 'mysql' %>
  port: <%= ENV['MYSQL_PORT'] || 3305 %>
  username: <%= ENV['MYSQL_USER'] || 'batch_user' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'batch' %>
  database: batch_dev

development:
  <<: *default # defaultの内容を展開する

test:
  <<: *default
  database: batch_test

production:
  <<: *default
  database: batch
